services:
  nelida-assistant:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nelida-assistant
    restart: unless-stopped
    
    # Variables de entorno desde archivo .env
    env_file:
      - .env
    
    # Variables de entorno adicionales para el container
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      
    # Volumes para persistencia de datos
    volumes:
      - ./data:/app/data:rw           # Base de datos SQLite
      - ./logs:/app/logs:rw           # Logs de la aplicación
      - /etc/localtime:/etc/localtime:ro  # Sincronizar timezone del host
      
    # Configuración de logging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        
    # Configuración de memoria y CPU
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
          
    # Configuración de red (opcional para debugging)
    networks:
      - nelida-network
      
    # Configuración de salud del container
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs/nelida.log') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Red personalizada (opcional)
networks:
  nelida-network:
    driver: bridge

# Volumes nombrados (alternativa a bind mounts)
volumes:
  nelida-data:
    driver: local
  nelida-logs:
    driver: local